name: zip_future
description: A Dart package for efficiently managing and executing multiple asynchronous operations using futures.
version: 1.1.0
repository: https://github.com/aelahmar/zip_future

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: 4.0.0
  test: 1.25.5
