name: zip_future
description: A Dart package for efficiently managing and executing multiple asynchronous operations (Futures) with advanced control over error handling, concurrency, and timeouts.
version: 1.2.0
repository: https://github.com/aelahmar/zip_future

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
# no external dependencies

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.5